version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - .:/var/www/ALED_API
    links:
      - db
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_reports
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/initialize_db_insert_data_set.sql:/docker-entrypoint-initdb.d//initialize_db_insert_data_set.sql
volumes:
  db_data:
